# CI for Sangria team project

name: SangriaBuildAndTest

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:

    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      
    - name: Set up Java and Maven
      uses: actions/setup-java@v2
      with:
        java-version: 8
        distribution: 'temurin'
        
    - name: Test auth
      working-directory: ./service-auth
      run: mvn clean test --file pom.xml -DskipTests=false
      
    - name: Test operation
      working-directory: ./service-operation
      run: mvn clean test --file pom.xml -DskipTests=false
      
    - name: Build client
      working-directory: ./service-client
      run: mvn -B package --file pom.xml
      
    
